/**
 * @fileoverview Data source for the Timeline Game containing 100 most important historical people
 * Each person includes their birth year, name, description of their contributions to the world, and Wikipedia link
 */

export const historicalPeople = [
  { year: -2589, name: "Khufu", description: "Egyptian pharaoh of the Fourth Dynasty who commissioned the Great Pyramid of Giza, the only surviving Wonder of the Ancient World, demonstrating the organizational power and mathematical sophistication of the Old Kingdom.", wikipedia: "https://en.wikipedia.org/wiki/Khufu" },
  { year: -1813, name: "Hammurabi", description: "Babylonian king who created the first known comprehensive written legal code with 282 laws, establishing principles of proportional justice ('eye for an eye') that influenced legal systems for millennia.", wikipedia: "https://en.wikipedia.org/wiki/Hammurabi" },
  { year: -1391, name: "Akhenaten", description: "Revolutionary Egyptian pharaoh who temporarily abandoned traditional polytheism to worship only Aten (the sun disc), fundamentally transforming Egyptian art, religion, and politics during the Amarna Period.", wikipedia: "https://en.wikipedia.org/wiki/Akhenaten" },
  { year: -1303, name: "Moses", description: "Hebrew prophet and lawgiver who led the Israelites out of Egyptian slavery in the Exodus, received the Ten Commandments on Mount Sinai, and established the covenant that became the foundation of Judaism.", wikipedia: "https://en.wikipedia.org/wiki/Moses" },
  { year: -1200, name: "David", description: "Second king of united Israel who conquered Jerusalem, established it as the eternal capital, defeated the Philistines, and became the model of the ideal Jewish king, inspiring the Psalms and messianic expectations.", wikipedia: "https://en.wikipedia.org/wiki/David" },
  { year: -800, name: "Homer", description: "Legendary ancient Greek poet who composed the Iliad and Odyssey, epic masterpieces that became the foundational works of Western literature and established heroic ideals that still resonate today.", wikipedia: "https://en.wikipedia.org/wiki/Homer" },
  { year: -628, name: "Zoroaster", description: "Persian prophet who founded Zoroastrianism, the first major monotheistic religion, introducing revolutionary concepts of good versus evil, final judgment, and the struggle between light and darkness that influenced Judaism, Christianity, and Islam.", wikipedia: "https://en.wikipedia.org/wiki/Zoroaster" },
  { year: -624, name: "Thales", description: "Greek philosopher from Miletus considered the first Western philosopher, who pioneered natural philosophy by seeking rational explanations for natural phenomena rather than mythological ones, founding Western scientific thinking.", wikipedia: "https://en.wikipedia.org/wiki/Thales_of_Miletus" },
  { year: -605, name: "Lao Tzu", description: "Legendary Chinese philosopher and founder of Taoism, who emphasized living in harmony with the Tao (the natural order), advocating simplicity, spontaneity, and non-action as paths to wisdom and peace.", wikipedia: "https://en.wikipedia.org/wiki/Laozi" },
  { year: -570, name: "Pythagoras", description: "Greek mathematician and philosopher who developed the famous Pythagorean theorem, founded a mystical school combining mathematics with spiritual beliefs, and discovered the mathematical basis of musical harmony.", wikipedia: "https://en.wikipedia.org/wiki/Pythagoras" },
  { year: -563, name: "Buddha", description: "Siddhartha Gautama, the spiritual teacher who founded Buddhism after achieving enlightenment under the Bodhi tree, teaching the Four Noble Truths and the Eightfold Path as the way to end suffering and achieve nirvana.", wikipedia: "https://en.wikipedia.org/wiki/Gautama_Buddha" },
  { year: -551, name: "Confucius", description: "Chinese philosopher whose teachings on ethics, proper relationships, and social harmony shaped East Asian civilization for over 2,500 years, emphasizing education, filial piety, and moral governance.", wikipedia: "https://en.wikipedia.org/wiki/Confucius" },
  { year: -540, name: "Mahavira", description: "The 24th and final Tirthankara of Jainism who developed the religion's core principles of ahimsa (non-violence), spiritual liberation through right conduct, and the eternal nature of the soul.", wikipedia: "https://en.wikipedia.org/wiki/Mahavira" },
  { year: -525, name: "Aeschylus", description: "Greek playwright who created the first great tragedies including 'The Oresteia,' established dramatic conventions like the trilogy format, and explored themes of justice, fate, and divine will that defined Western theater.", wikipedia: "https://en.wikipedia.org/wiki/Aeschylus" },
  { year: -496, name: "Sophocles", description: "Greek tragedian who perfected dramatic structure and wrote masterpieces like 'Oedipus Rex' and 'Antigone,' exploring themes of fate, moral responsibility, and the conflict between divine law and human will that continue to resonate in modern theater.", wikipedia: "https://en.wikipedia.org/wiki/Sophocles" },
  { year: -484, name: "Herodotus", description: "Greek historian known as the 'Father of History' for his systematic approach to recording events, traveling extensively to gather firsthand accounts and establishing the discipline of historical inquiry based on evidence rather than myth.", wikipedia: "https://en.wikipedia.org/wiki/Herodotus" },
  { year: -470, name: "Socrates", description: "Greek philosopher who revolutionized philosophy by focusing on ethics and self-knowledge, developing the Socratic method of questioning to expose ignorance and pursue truth, profoundly influencing Western philosophical thought despite writing nothing himself.", wikipedia: "https://en.wikipedia.org/wiki/Socrates" },
  { year: -460, name: "Hippocrates", description: "Greek physician who revolutionized medicine by separating it from superstition and religion, establishing medicine as a rational science based on observation and natural causes, and creating the Hippocratic Oath that still guides medical ethics today.", wikipedia: "https://en.wikipedia.org/wiki/Hippocrates" },
  { year: -428, name: "Plato", description: "Greek philosopher who founded the Academy in Athens and wrote philosophical dialogues exploring justice, truth, and the ideal state, establishing the foundations of Western philosophy and political theory through works like 'The Republic.'", wikipedia: "https://en.wikipedia.org/wiki/Plato" },
  { year: -384, name: "Aristotle", description: "Greek philosopher and scientist who systematized logic, ethics, politics, and natural science, tutored Alexander the Great, and created comprehensive frameworks for understanding reality that dominated Western thought for over two millennia.", wikipedia: "https://en.wikipedia.org/wiki/Aristotle" },
  { year: -356, name: "Alexander the Great", description: "Macedonian king who created one of history's largest empires stretching from Greece to India, spreading Hellenistic culture across the known world and fundamentally connecting East and West through conquest, trade, and cultural exchange.", wikipedia: "https://en.wikipedia.org/wiki/Alexander_the_Great" },
  { year: -287, name: "Archimedes", description: "Greek mathematician, physicist, and inventor who discovered fundamental principles of hydrostatics and mechanics, calculated pi with remarkable accuracy, and created ingenious machines including the Archimedes screw that revolutionized engineering.", wikipedia: "https://en.wikipedia.org/wiki/Archimedes" },
  { year: -259, name: "Qin Shi Huang", description: "First Emperor of unified China who ended the Warring States period, built much of what became the Great Wall, standardized Chinese writing and currency, and established administrative systems that unified Chinese civilization for millennia.", wikipedia: "https://en.wikipedia.org/wiki/Qin_Shi_Huang" },
  { year: -106, name: "Cicero", description: "Roman orator, philosopher, and statesman who defended the Roman Republic against autocracy, created Latin philosophical vocabulary that influenced Western thought, and established rhetorical principles still taught in schools today.", wikipedia: "https://en.wikipedia.org/wiki/Cicero" },
  { year: -100, name: "Julius Caesar", description: "Roman general, statesman, and dictator who conquered Gaul, crossed the Rubicon to start a civil war, reformed the Roman calendar, and transformed the Roman Republic into an empire before his assassination on the Ides of March.", wikipedia: "https://en.wikipedia.org/wiki/Julius_Caesar" },
  { year: -69, name: "Cleopatra VII", description: "Last active pharaoh of Egypt who forged political and romantic alliances with Julius Caesar and Mark Antony, became a symbol of female power and intelligence, and whose death marked the end of the Ptolemaic dynasty and Egypt's independence.", wikipedia: "https://en.wikipedia.org/wiki/Cleopatra" },
  { year: -63, name: "Augustus", description: "First Roman Emperor who ended the civil wars that destroyed the Republic, established the Pax Romana that brought peace and prosperity for two centuries, and created the imperial system that would govern the Roman world for centuries.", wikipedia: "https://en.wikipedia.org/wiki/Augustus" },
  { year: -4, name: "Jesus Christ", description: "Jewish religious teacher whose teachings about love, forgiveness, and salvation founded Christianity, profoundly influencing Western civilization, moral philosophy, art, and culture while becoming the most influential figure in human history.", wikipedia: "https://en.wikipedia.org/wiki/Jesus" },
  { year: 121, name: "Marcus Aurelius", description: "Roman Emperor and Stoic philosopher whose personal journal 'Meditations' became one of the greatest works of ancient philosophy, combining the burdens of imperial power with deep reflection on virtue, duty, and the meaning of life.", wikipedia: "https://en.wikipedia.org/wiki/Marcus_Aurelius" },
  { year: 354, name: "Augustine of Hippo", description: "Christian theologian and philosopher who synthesized Christianity with classical philosophy, wrote 'Confessions' and 'The City of God,' and profoundly influenced medieval thought, the Protestant Reformation, and Western Christianity.", wikipedia: "https://en.wikipedia.org/wiki/Augustine_of_Hippo" },
  { year: 570, name: "Muhammad", description: "Prophet and founder of Islam who received the Quran through divine revelation, united the Arabian Peninsula under Islamic rule, and established a religion that would become the world's second-largest faith, profoundly shaping global civilization.", wikipedia: "https://en.wikipedia.org/wiki/Muhammad" },
  { year: 742, name: "Charlemagne", description: "Frankish king who united much of Western Europe under the Carolingian Empire, was crowned Holy Roman Emperor by the Pope, promoted the Carolingian Renaissance of learning, and became the model of medieval Christian kingship.", wikipedia: "https://en.wikipedia.org/wiki/Charlemagne" },
  { year: 980, name: "Ibn Sina (Avicenna)", description: "Persian polymath whose medical encyclopedia 'The Canon of Medicine' became the standard medical text in Europe and the Islamic world for centuries, while his philosophical works bridged Aristotelian thought with Islamic theology.", wikipedia: "https://en.wikipedia.org/wiki/Avicenna" },
  { year: 1040, name: "Omar Khayyam", description: "Persian mathematician, astronomer, and poet who made significant advances in algebra, reformed the calendar with remarkable accuracy, and wrote the famous 'Rubaiyat' that celebrated life's pleasures and philosophical contemplation.", wikipedia: "https://en.wikipedia.org/wiki/Omar_Khayyam" },
  { year: 1126, name: "Ibn Rushd (Averroes)", description: "Andalusian philosopher who preserved and commented on Aristotelian philosophy, bridging Islamic, Jewish, and Christian intellectual traditions while defending reason against religious fundamentalism and profoundly influencing medieval European thought through his comprehensive commentaries on Aristotle.", wikipedia: "https://en.wikipedia.org/wiki/Averroes" },
  { year: 1162, name: "Genghis Khan", description: "Mongol leader who united the Mongol tribes and created the largest contiguous land empire in history, stretching from Eastern Europe to the Pacific Ocean, revolutionizing warfare, trade routes, and cultural exchange while establishing religious tolerance and meritocracy across his vast domain.", wikipedia: "https://en.wikipedia.org/wiki/Genghis_Khan" },
  { year: 1214, name: "Roger Bacon", description: "English philosopher and scientist who promoted empirical methods and scientific experimentation over purely theoretical approaches, advocating for direct observation and mathematical analysis while making advances in optics, alchemy, and astronomy during the medieval period.", wikipedia: "https://en.wikipedia.org/wiki/Roger_Bacon" },
  { year: 1225, name: "Thomas Aquinas", description: "Italian theologian and philosopher who synthesized Aristotelian philosophy with Christian doctrine, creating the comprehensive theological system of Scholasticism that dominated medieval thought and established the foundation for Catholic philosophical theology through works like 'Summa Theologica.'", wikipedia: "https://en.wikipedia.org/wiki/Thomas_Aquinas" },
  { year: 1254, name: "Marco Polo", description: "Venetian explorer whose extensive travels to Asia along the Silk Road opened new trade routes and cultural exchange between East and West, documenting Chinese customs, technology, and geography in 'The Travels of Marco Polo' that inspired future exploration and commerce.", wikipedia: "https://en.wikipedia.org/wiki/Marco_Polo" },
  { year: 1265, name: "Dante Alighieri", description: "Italian poet who wrote 'The Divine Comedy,' a monumental epic poem that established Italian as a literary language, created the modern concept of Hell, Purgatory, and Paradise, and profoundly influenced world literature through its synthesis of classical philosophy with Christian theology.", wikipedia: "https://en.wikipedia.org/wiki/Dante_Alighieri" },
  { year: 1304, name: "Petrarch", description: "Italian scholar and poet who initiated the Renaissance humanist movement by rediscovering classical texts, developing the concept of the 'Dark Ages,' and creating the Petrarchan sonnet form that influenced poetry for centuries while promoting individual achievement and secular learning.", wikipedia: "https://en.wikipedia.org/wiki/Petrarch" },
  { year: 1343, name: "Geoffrey Chaucer", description: "English poet whose 'Canterbury Tales' helped establish English as a literary language equal to Latin and French, creating vivid character portraits that captured medieval society while pioneering narrative techniques that influenced storytelling for centuries.", wikipedia: "https://en.wikipedia.org/wiki/Geoffrey_Chaucer" },
  { year: 1386, name: "Donatello", description: "Italian sculptor who revived classical sculpture techniques during the Renaissance, creating the first freestanding nude sculpture since antiquity with his bronze 'David' and pioneering realistic human expression and proportion that influenced Renaissance art for generations.", wikipedia: "https://en.wikipedia.org/wiki/Donatello" },
  { year: 1394, name: "Johannes Gutenberg", description: "German inventor whose movable-type printing press democratized knowledge by making books affordable and widely available, accelerating the Renaissance, Protestant Reformation, and Scientific Revolution while fundamentally transforming education and information dissemination.", wikipedia: "https://en.wikipedia.org/wiki/Johannes_Gutenberg" },
  { year: 1412, name: "Joan of Arc", description: "French peasant girl who claimed divine visions instructing her to expel English invaders, convinced the Dauphin to let her lead French forces, lifted the siege of Orléans, and inspired French resistance during the Hundred Years' War before being captured, tried for heresy, and burned at the stake.", wikipedia: "https://en.wikipedia.org/wiki/Joan_of_Arc" },
  { year: 1449, name: "Lorenzo de' Medici", description: "Italian statesman and patron known as 'Lorenzo the Magnificent' who fostered Renaissance art and humanism in Florence, supporting artists like Michelangelo and Botticelli while maintaining political stability and promoting cultural achievement that made Florence the center of Renaissance civilization.", wikipedia: "https://en.wikipedia.org/wiki/Lorenzo_de%27_Medici" },
  { year: 1452, name: "Leonardo da Vinci", description: "Italian polymath whose genius spanned art, science, engineering, and invention, creating masterpieces like the 'Mona Lisa' and 'The Last Supper' while designing flying machines, studying human anatomy, and making scientific observations that epitomized Renaissance intellectual curiosity and achievement.", wikipedia: "https://en.wikipedia.org/wiki/Leonardo_da_Vinci" },
  { year: 1469, name: "Niccolò Machiavelli", description: "Italian political philosopher who wrote 'The Prince,' revolutionizing political theory by separating politics from morality, advocating pragmatic statecraft over idealistic governance, and influencing modern concepts of political realism and effective leadership through his analysis of power dynamics.", wikipedia: "https://en.wikipedia.org/wiki/Niccolò_Machiavelli" },
  { year: 1473, name: "Nicolaus Copernicus", description: "Polish astronomer who proposed the heliocentric model of the solar system, placing the Sun rather than Earth at the center, revolutionizing astronomy and cosmology while challenging medieval worldviews and laying the foundation for modern astronomical science.", wikipedia: "https://en.wikipedia.org/wiki/Nicolaus_Copernicus" },
  { year: 1475, name: "Michelangelo", description: "Italian Renaissance artist who created immortal masterpieces in sculpture, painting, and architecture including the 'David,' the Sistine Chapel ceiling, and St. Peter's Basilica dome, embodying the Renaissance ideal of the complete artist while pushing artistic boundaries and inspiring centuries of artists.", wikipedia: "https://en.wikipedia.org/wiki/Michelangelo" },
  { year: 1478, name: "Thomas More", description: "English lawyer, philosopher, and statesman who wrote 'Utopia' describing an ideal society, served as Lord Chancellor under Henry VIII, but was executed for refusing to accept the king's break from Rome, becoming a martyr for conscience and religious principle.", wikipedia: "https://en.wikipedia.org/wiki/Thomas_More" },
  { year: 1483, name: "Martin Luther", description: "German monk who initiated the Protestant Reformation by challenging Catholic Church practices, posting his Ninety-Five Theses, translating the Bible into German, and establishing principles of salvation by faith alone that permanently divided Christianity and transformed European society.", wikipedia: "https://en.wikipedia.org/wiki/Martin_Luther" },
  { year: 1483, name: "Raphael", description: "Italian Renaissance painter known for his harmonious and graceful artistic style, creating masterpieces like 'The School of Athens' and numerous Madonnas that perfectly balanced classical ideals with Christian themes while influencing artistic standards of beauty and composition for centuries.", wikipedia: "https://en.wikipedia.org/wiki/Raphael" },
  { year: 1485, name: "Hernán Cortés", description: "Spanish conquistador who conquered the powerful Aztec Empire with a small force, fundamentally reshaping the Americas through the introduction of European diseases, technology, and culture while beginning the Spanish colonial period that would dominate Latin America for centuries.", wikipedia: "https://en.wikipedia.org/wiki/Hernán_Cortés" },
  { year: 1491, name: "Henry VIII", description: "English king who broke from Rome to divorce Catherine of Aragon and marry Anne Boleyn, established the Church of England with himself as head, strengthened royal power through the dissolution of monasteries, and fundamentally altered English religious and political life through his six marriages and quest for a male heir.", wikipedia: "https://en.wikipedia.org/wiki/Henry_VIII" },
  { year: 1564, name: "William Shakespeare", description: "English playwright and poet whose unparalleled literary works including 'Hamlet,' 'Romeo and Juliet,' and 'Macbeth' defined literature and explored the depths of human psychology, creating characters and phrases that remain central to world culture while establishing the foundations of modern drama.", wikipedia: "https://en.wikipedia.org/wiki/William_Shakespeare" },
  { year: 1564, name: "Galileo Galilei", description: "Italian astronomer and physicist who supported Copernican heliocentrism through telescopic observations, advanced scientific method through experimentation and mathematical analysis, and faced persecution by the Catholic Church for defending ideas that revolutionized our understanding of the cosmos.", wikipedia: "https://en.wikipedia.org/wiki/Galileo_Galilei" },
  { year: 1571, name: "Johannes Kepler", description: "German astronomer who discovered the three fundamental laws of planetary motion, proving that planets orbit the Sun in elliptical rather than circular paths, advancing celestial mechanics and laying crucial groundwork for Newton's law of universal gravitation.", wikipedia: "https://en.wikipedia.org/wiki/Johannes_Kepler" },
  { year: 1588, name: "Thomas Hobbes", description: "English philosopher who wrote 'Leviathan,' arguing that absolute sovereignty is necessary to prevent the 'war of all against all' in the state of nature, profoundly influencing political theory and social contract philosophy while advocating for strong central government.", wikipedia: "https://en.wikipedia.org/wiki/Thomas_Hobbes" },
  { year: 1596, name: "René Descartes", description: "French philosopher who developed modern philosophical method based on systematic doubt and rational inquiry, famously declaring 'I think, therefore I am,' while also advancing analytical geometry and establishing the foundation for modern Western philosophy through his separation of mind and matter.", wikipedia: "https://en.wikipedia.org/wiki/René_Descartes" },
  { year: 1606, name: "Rembrandt", description: "Dutch painter whose innovative use of light and shadow (chiaroscuro) and psychological depth in portraits revolutionized Western art, creating masterpieces like 'The Night Watch' and numerous self-portraits that captured human emotion and character with unprecedented realism and artistic skill.", wikipedia: "https://en.wikipedia.org/wiki/Rembrandt" },
  { year: 1632, name: "John Locke", description: "English philosopher whose ideas on natural rights, government by consent, and religious tolerance profoundly influenced democratic revolutions, particularly the American Revolution and Constitution, establishing the theoretical foundation for modern liberal democracy and individual liberty.", wikipedia: "https://en.wikipedia.org/wiki/John_Locke" },
  { year: 1642, name: "Isaac Newton", description: "English mathematician and physicist who discovered the laws of motion and universal gravitation, developed calculus, and explained the behavior of objects on Earth and in the heavens through mathematical principles, revolutionizing science and establishing the foundation of classical physics.", wikipedia: "https://en.wikipedia.org/wiki/Isaac_Newton" },
  { year: 1685, name: "Johann Sebastian Bach", description: "German composer who achieved mathematical perfection in music through complex counterpoint and harmonic innovation, creating masterpieces like the 'Brandenburg Concertos' and 'The Well-Tempered Clavier' that influenced all subsequent composers and established the highest standards of musical artistry.", wikipedia: "https://en.wikipedia.org/wiki/Johann_Sebastian_Bach" },
  { year: 1694, name: "Voltaire", description: "French Enlightenment writer and philosopher who championed civil liberties, freedom of religion, and free trade while attacking religious dogma and political oppression through satirical works like 'Candide,' becoming a symbol of intellectual freedom and rational thought that influenced democratic movements worldwide.", wikipedia: "https://en.wikipedia.org/wiki/Voltaire" },
  { year: 1706, name: "Benjamin Franklin", description: "American polymath who advanced science through experiments with electricity, served as diplomat securing French support during the Revolutionary War, helped draft the Declaration of Independence and Constitution, and embodied democratic principles while becoming one of the most influential Founding Fathers.", wikipedia: "https://en.wikipedia.org/wiki/Benjamin_Franklin" },
  { year: 1712, name: "Jean-Jacques Rousseau", description: "French philosopher whose ideas on democracy, education, and the social contract profoundly influenced the French Revolution and modern political thought, arguing that civilization corrupts natural human goodness while advocating for popular sovereignty and individual freedom.", wikipedia: "https://en.wikipedia.org/wiki/Jean-Jacques_Rousseau" },
  { year: 1724, name: "Immanuel Kant", description: "German philosopher who revolutionized ethics, metaphysics, and epistemology through works like 'Critique of Pure Reason,' establishing the categorical imperative as a foundation for moral behavior and arguing that reason has limits while duty and moral law are universal and absolute.", wikipedia: "https://en.wikipedia.org/wiki/Immanuel_Kant" },
  { year: 1732, name: "George Washington", description: "American general who led Continental Army to victory in the Revolutionary War and became the first President of the United States, establishing crucial precedents for democratic leadership including peaceful transfer of power and the two-term tradition that shaped American democracy.", wikipedia: "https://en.wikipedia.org/wiki/George_Washington" },
  { year: 1743, name: "Thomas Jefferson", description: "American statesman who wrote the Declaration of Independence proclaiming that 'all men are created equal,' served as third President, championed individual rights and limited government, and completed the Louisiana Purchase that doubled the nation's size while embodying Enlightenment ideals in democratic governance.", wikipedia: "https://en.wikipedia.org/wiki/Thomas_Jefferson" },
  { year: 1756, name: "Wolfgang Amadeus Mozart", description: "Austrian composer whose musical genius produced over 600 works of unparalleled beauty and complexity, including operas like 'The Magic Flute,' symphonies, concertos, and chamber music that achieved perfect balance between technical mastery and emotional expression, influencing all subsequent classical music.", wikipedia: "https://en.wikipedia.org/wiki/Wolfgang_Amadeus_Mozart" },
  { year: 1769, name: "Napoleon Bonaparte", description: "French military leader and emperor who spread democratic ideals and legal reforms across Europe through conquest, created the Napoleonic Code that influenced legal systems worldwide, and fundamentally reshaped European politics while promoting meritocracy and nationalism.", wikipedia: "https://en.wikipedia.org/wiki/Napoleon" },
  { year: 1770, name: "Ludwig van Beethoven", description: "German composer who bridged Classical and Romantic periods through revolutionary music that expressed individual emotion and struggle, overcoming deafness to create masterpieces like the Ninth Symphony that expanded the possibilities of musical expression and inspired generations of artists.", wikipedia: "https://en.wikipedia.org/wiki/Ludwig_van_Beethoven" },
  { year: 1775, name: "Jane Austen", description: "English novelist whose witty social commentary and brilliant character development in novels like 'Pride and Prejudice' and 'Emma' revolutionized literature by focusing on women's inner lives and social constraints while establishing the modern novel form with psychological realism.", wikipedia: "https://en.wikipedia.org/wiki/Jane_Austen" },
  { year: 1809, name: "Charles Darwin", description: "English naturalist who proposed evolution by natural selection in 'On the Origin of Species,' revolutionizing biology by explaining the diversity of life through scientific evidence rather than religious doctrine, fundamentally changing humanity's understanding of its place in nature.", wikipedia: "https://en.wikipedia.org/wiki/Charles_Darwin" },
  { year: 1809, name: "Abraham Lincoln", description: "American president who preserved the Union during the Civil War, issued the Emancipation Proclamation ending slavery, and redefined democratic government through his vision of 'government of the people, by the people, for the people' while becoming a martyr for equality and freedom.", wikipedia: "https://en.wikipedia.org/wiki/Abraham_Lincoln" },
  { year: 1818, name: "Karl Marx", description: "German philosopher and economist whose critique of capitalism in 'Das Kapital' and 'The Communist Manifesto' analyzed class struggle and predicted the eventual overthrow of capitalist systems, profoundly influencing political movements and socialist revolutions worldwide.", wikipedia: "https://en.wikipedia.org/wiki/Karl_Marx" },
  { year: 1820, name: "Florence Nightingale", description: "English nurse who founded modern nursing through her work during the Crimean War, dramatically improved hospital sanitation and patient care, and used statistical analysis to demonstrate the importance of hygiene in reducing mortality rates, revolutionizing healthcare practices.", wikipedia: "https://en.wikipedia.org/wiki/Florence_Nightingale" },
  { year: 1822, name: "Louis Pasteur", description: "French microbiologist who proved germ theory of disease, developed pasteurization to make food safer, created vaccines for rabies and anthrax, and established the scientific foundation of microbiology while saving countless lives through his medical breakthroughs.", wikipedia: "https://en.wikipedia.org/wiki/Louis_Pasteur" },
  { year: 1831, name: "James Clerk Maxwell", description: "Scottish physicist who unified electricity and magnetism through Maxwell's equations, predicting the existence of electromagnetic waves including light, radio waves, and X-rays, laying the theoretical foundation for modern physics and technologies like wireless communication and electronics.", wikipedia: "https://en.wikipedia.org/wiki/James_Clerk_Maxwell" },
  { year: 1833, name: "Alfred Nobel", description: "Swedish inventor and industrialist who invented dynamite and other explosives, amassed a fortune from armaments, then established the Nobel Prizes to honor achievements in physics, chemistry, medicine, literature, and peace, creating the world's most prestigious awards for human achievement.", wikipedia: "https://en.wikipedia.org/wiki/Alfred_Nobel" },
  { year: 1844, name: "Friedrich Nietzsche", description: "German philosopher who challenged traditional morality and religion, proclaimed the 'death of God,' developed concepts like the 'Übermensch' and 'will to power,' and profoundly influenced existentialist thought while questioning the foundations of Western values and ethics.", wikipedia: "https://en.wikipedia.org/wiki/Friedrich_Nietzsche" },
  { year: 1847, name: "Thomas Edison", description: "American inventor whose practical innovations in electricity, communication, and recording transformed modern life, creating the light bulb, phonograph, and motion picture camera while establishing the first industrial research laboratory and holding over 1,000 patents.", wikipedia: "https://en.wikipedia.org/wiki/Thomas_Edison" },
  { year: 1856, name: "Sigmund Freud", description: "Austrian neurologist who founded psychoanalysis, revolutionizing understanding of the human psyche through concepts like the unconscious mind, dream interpretation, and psychosexual development, fundamentally changing psychology and culture." },
  { year: 1856, name: "Nikola Tesla", description: "Serbian-American inventor and electrical engineer who developed alternating current electrical systems, wireless technology, and numerous innovations that laid the foundation for modern electrical power and wireless communication." },
  { year: 1867, name: "Marie Curie", description: "Polish-French physicist and chemist who discovered radioactivity, isolated radium and polonium, became the first woman to win a Nobel Prize, and remains the only person to win Nobel Prizes in two different sciences." },
  { year: 1869, name: "Mahatma Gandhi", description: "Indian independence leader who pioneered satyagraha (nonviolent resistance), led India to independence from British rule, and inspired civil rights movements worldwide through his philosophy of non-violence and truth." },
  { year: 1879, name: "Albert Einstein", description: "German-American theoretical physicist whose special and general theories of relativity revolutionized our understanding of space, time, gravity, and energy, fundamentally changing physics and leading to nuclear technology." },
  { year: 1881, name: "Pablo Picasso", description: "Spanish artist who co-founded Cubism and revolutionized 20th-century art by fragmenting objects into geometric forms, creating masterpieces like 'Les Demoiselles d'Avignon' and 'Guernica' while constantly evolving his style through Blue, Rose, and other periods that influenced generations of artists.", wikipedia: "https://en.wikipedia.org/wiki/Pablo_Picasso" },
  { year: 1889, name: "Adolf Hitler", description: "Austrian-German dictator whose fascist Nazi ideology led to World War II, the Holocaust that murdered six million Jews, and unprecedented destruction across Europe, demonstrating the catastrophic consequences of totalitarianism, racism, and unchecked political power.", wikipedia: "https://en.wikipedia.org/wiki/Adolf_Hitler" },
  { year: 1892, name: "J.R.R. Tolkien", description: "English author and philologist who created the fantasy world of Middle-earth in 'The Hobbit' and 'The Lord of the Rings,' establishing the foundations of modern fantasy literature through his detailed mythology, languages, and timeless themes of good versus evil.", wikipedia: "https://en.wikipedia.org/wiki/J._R._R._Tolkien" },
  { year: 1901, name: "Walt Disney", description: "American animator and entrepreneur who revolutionized entertainment by creating Mickey Mouse, pioneering feature-length animated films like 'Snow White,' and building Disneyland, fundamentally changing popular culture while establishing animation as a major art form and global entertainment industry.", wikipedia: "https://en.wikipedia.org/wiki/Walt_Disney" },
  { year: 1904, name: "J. Robert Oppenheimer", description: "American physicist who led the Manhattan Project that developed the atomic bomb, ushering in the nuclear age during World War II, then became an advocate for international control of nuclear weapons while grappling with the moral implications of his scientific achievement.", wikipedia: "https://en.wikipedia.org/wiki/J._Robert_Oppenheimer" },
  { year: 1908, name: "Lyndon B. Johnson", description: "American president who advanced civil rights through the Civil Rights Act and Voting Rights Act, launched the Great Society programs to fight poverty and inequality, but became controversial for escalating the Vietnam War during the turbulent 1960s.", wikipedia: "https://en.wikipedia.org/wiki/Lyndon_B._Johnson" },
  { year: 1918, name: "Nelson Mandela", description: "South African anti-apartheid leader who spent 27 years in prison for fighting racial oppression, then became president and led the peaceful transition to democracy, becoming a global symbol of reconciliation, forgiveness, and human rights through his moral leadership.", wikipedia: "https://en.wikipedia.org/wiki/Nelson_Mandela" },
  { year: 1929, name: "Martin Luther King Jr.", description: "American civil rights leader who used nonviolent protest and powerful oratory to advance racial equality, delivered the famous 'I Have a Dream' speech, and became a martyr for justice after his assassination, fundamentally changing American society and inspiring civil rights movements worldwide.", wikipedia: "https://en.wikipedia.org/wiki/Martin_Luther_King_Jr." },
  { year: 1930, name: "Neil Armstrong", description: "American astronaut and engineer who became the first human to walk on the Moon during the Apollo 11 mission, uttering the famous words 'That's one small step for man, one giant leap for mankind' while achieving humanity's greatest exploration milestone.", wikipedia: "https://en.wikipedia.org/wiki/Neil_Armstrong" },
  { year: 1942, name: "Stephen Hawking", description: "English theoretical physicist who advanced understanding of black holes and cosmology despite being diagnosed with ALS, wrote the bestselling 'A Brief History of Time' that made complex physics accessible to the public, and became an icon of scientific perseverance and intellectual achievement.", wikipedia: "https://en.wikipedia.org/wiki/Stephen_Hawking" },
  { year: 1946, name: "Bill Clinton", description: "American president who presided over economic prosperity and technological advancement in the 1990s, survived impeachment proceedings, implemented centrist policies that moved the Democratic Party toward the political center, and became known for his charismatic communication skills and political acumen.", wikipedia: "https://en.wikipedia.org/wiki/Bill_Clinton" },
  { year: 1955, name: "Bill Gates", description: "American entrepreneur who co-founded Microsoft and revolutionized personal computing by making computers user-friendly and accessible, became the world's richest person, then dedicated his wealth to global health and education initiatives through the Bill & Melinda Gates Foundation.", wikipedia: "https://en.wikipedia.org/wiki/Bill_Gates" },
  { year: 1955, name: "Steve Jobs", description: "American entrepreneur who co-founded Apple and revolutionized multiple industries through innovative products like the personal computer, iPod, iPhone, and iPad, fundamentally changing how humans interact with technology." },
  { year: 1971, name: "Elon Musk", description: "South African-American entrepreneur and innovator advancing electric vehicles through Tesla, commercial spaceflight through SpaceX, and various other technologies aimed at sustainable energy and making humanity multiplanetary." },
];

/**
 * Shuffle array using Fisher-Yates algorithm
 */
export function shufflePeople(people) {
  const shuffled = [...people];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

/**
 * Get a random subset of people for the game
 */
export function getRandomPeopleSet(count = 20) {
  const shuffled = shufflePeople(historicalPeople);
  return shuffled.slice(0, count);
}

/**
 * Sort people by year (for verification)
 */
export function sortPeopleByYear(people) {
  return [...people].sort((a, b) => a.year - b.year);
}
