/**
 * @fileoverview Data source for the Timeline Game containing 100 most important historical conflicts
 * Each conflict includes the start year, name, description of its significance and impact, and Wikipedia link
 */

export const historicalConflicts = [
  { year: -3200, name: "Early Mesopotamian Wars", description: "The first recorded warfare between Sumerian city-states like Ur, Uruk, and Lagash established fundamental patterns of territorial conflict, siege warfare, and diplomatic treaties that would influence military strategy for millennia.", wikipedia: "https://en.wikipedia.org/wiki/Sumerian_military" },
  { year: -2686, name: "Unification of Egypt", description: "Pharaoh Menes (Narmer) conquered Upper and Lower Egypt through a series of decisive battles, creating the first unified Egyptian kingdom and establishing the pharaonic system that would endure for over 3,000 years.", wikipedia: "https://en.wikipedia.org/wiki/Narmer" },
  { year: -1600, name: "Hyksos Invasion of Egypt", description: "Foreign Semitic rulers conquered Lower Egypt, introducing revolutionary military technologies including horse-drawn chariots, composite bows, and bronze weapons that transformed ancient Near Eastern warfare.", wikipedia: "https://en.wikipedia.org/wiki/Hyksos" },
  { year: -1274, name: "Battle of Kadesh", description: "The massive chariot battle between Pharaoh Ramesses II and Hittite King Muwatalli II involved over 5,000 chariots and resulted in one of history's first recorded peace treaties, establishing diplomatic precedents still used today.", wikipedia: "https://en.wikipedia.org/wiki/Battle_of_Kadesh" },
  { year: -1200, name: "Bronze Age Collapse", description: "A mysterious period of widespread destruction across the Eastern Mediterranean that ended the Mycenaean, Hittite, and other major civilizations, possibly caused by climate change, internal rebellions, and invasions by the enigmatic 'Sea Peoples.'", wikipedia: "https://en.wikipedia.org/wiki/Late_Bronze_Age_collapse" },
  { year: -1100, name: "Dorian Invasion", description: "Greek tribal migrations from the north that destroyed the sophisticated Mycenaean palace civilization, ushering in the Greek Dark Ages but ultimately leading to the emergence of classical Greek city-states and culture.", wikipedia: "https://en.wikipedia.org/wiki/Dorian_invasion" },
  { year: -800, name: "Assyrian Conquests", description: "The Assyrian Empire's brutal military campaigns created the first multi-ethnic empire in the Middle East, pioneering iron weapons, siege engines, and administrative systems that influenced all subsequent empires.", wikipedia: "https://en.wikipedia.org/wiki/Neo-Assyrian_Empire" },
  { year: -776, name: "First Messenian War", description: "Sparta's 20-year conquest of the fertile Messenian region doubled their territory and enslaved the entire population as helots, creating the economic foundation for Sparta's unique militaristic society.", wikipedia: "https://en.wikipedia.org/wiki/First_Messenian_War" },
  { year: -722, name: "Assyrian Conquest of Israel", description: "King Sargon II's destruction of the northern kingdom of Israel dispersed the ten lost tribes and ended Hebrew political independence until the 20th century, profoundly shaping Jewish identity and diaspora culture.", wikipedia: "https://en.wikipedia.org/wiki/Assyrian_captivity" },
  { year: -586, name: "Babylonian Conquest of Judah", description: "Nebuchadnezzar II's siege of Jerusalem destroyed Solomon's Temple and forced the Jewish elite into Babylonian exile, a traumatic event that transformed Judaism from a temple-based to a text-based religion.", wikipedia: "https://en.wikipedia.org/wiki/Babylonian_captivity" },
  { year: -560, name: "Lydian-Persian Wars", description: "Cyrus the Great's conquest of the wealthy kingdom of Lydia under King Croesus not only expanded Persian power into Asia Minor but also brought the world's first minted coins under Persian control, revolutionizing ancient economics.", wikipedia: "https://en.wikipedia.org/wiki/Battle_of_Pteria" },
  { year: -539, name: "Persian Conquest of Babylon", description: "Cyrus the Great's bloodless capture of Babylon created the largest empire the world had yet seen, stretching from India to Greece, and established the Persian model of tolerant multi-ethnic rule that influenced all subsequent empires.", wikipedia: "https://en.wikipedia.org/wiki/Fall_of_Babylon" },
  { year: -499, name: "Ionian Revolt", description: "Greek cities in Persian-controlled Asia Minor launched a desperate rebellion against Persian rule, sparking the great Greco-Persian Wars that would define the relationship between East and West for centuries.", wikipedia: "https://en.wikipedia.org/wiki/Ionian_Revolt" },
  { year: -490, name: "First Persian Invasion of Greece", description: "Darius I's punitive expedition against Athens culminated in the legendary Battle of Marathon, where vastly outnumbered Athenians proved that Persian forces could be defeated, inspiring Greek resistance and confidence.", wikipedia: "https://en.wikipedia.org/wiki/First_Persian_invasion_of_Greece" },
  { year: -480, name: "Second Persian Invasion of Greece", description: "Xerxes' massive invasion force of over 200,000 men was ultimately defeated by united Greek city-states at Thermopylae, Salamis, and Plataea, preserving Greek independence and allowing classical civilization to flourish.", wikipedia: "https://en.wikipedia.org/wiki/Second_Persian_invasion_of_Greece" },
  { year: -431, name: "Peloponnesian War", description: "The devastating 27-year conflict between democratic Athens and militaristic Sparta tore apart the Greek world, ending Athens' golden age and weakening all Greek city-states enough for eventual Macedonian conquest.", wikipedia: "https://en.wikipedia.org/wiki/Peloponnesian_War" },
  { year: -334, name: "Alexander's Conquests", description: "Alexander the Great's lightning campaigns across three continents created a vast empire from Egypt to India, spreading Hellenistic culture and establishing cities that remained centers of learning for centuries.", wikipedia: "https://en.wikipedia.org/wiki/Wars_of_Alexander_the_Great" },
  { year: -264, name: "First Punic War", description: "Rome's 23-year struggle with Carthage for control of Sicily marked Rome's first major overseas expansion and the beginning of its transformation from a regional Italian power to Mediterranean hegemon.", wikipedia: "https://en.wikipedia.org/wiki/First_Punic_War" },
  { year: -218, name: "Second Punic War", description: "Hannibal's audacious march across the Alps with elephants and his victories at Cannae nearly destroyed Rome, but Roman resilience and Scipio Africanus' eventual victory in Africa secured Roman dominance.", wikipedia: "https://en.wikipedia.org/wiki/Second_Punic_War" },
  { year: -149, name: "Third Punic War", description: "Rome's complete destruction of Carthage and the legendary salting of its fields eliminated Rome's greatest rival and demonstrated the ruthless determination that would characterize Roman imperial expansion.", wikipedia: "https://en.wikipedia.org/wiki/Third_Punic_War" },
  { year: -113, name: "Cimbrian War", description: "Germanic tribes from the north invaded the Roman Republic in a massive migration that brought terror to Roman citizens as the barbarian hordes defeated several Roman armies and nearly reached Rome itself before being stopped by Marius.", wikipedia: "https://en.wikipedia.org/wiki/Cimbrian_War" },
  { year: -58, name: "Gallic Wars", description: "Julius Caesar's eight-year conquest of Gaul brought all of modern France, Belgium, and parts of Germany under Roman control, demonstrating Roman military superiority while providing Caesar with the wealth and veteran legions needed for his later civil war.", wikipedia: "https://en.wikipedia.org/wiki/Gallic_Wars" },
  { year: -49, name: "Caesar's Civil War", description: "Julius Caesar's crossing of the Rubicon River with his army initiated a civil war that would destroy the Roman Republic, as his conflict with Pompey and the Senate ultimately led to his dictatorship and assassination, paving the way for the Roman Empire.", wikipedia: "https://en.wikipedia.org/wiki/Caesar%27s_civil_war" },
  { year: -32, name: "Final War of the Roman Republic", description: "Octavian's decisive naval victory over Mark Antony and Cleopatra at the Battle of Actium ended the last civil war of the Roman Republic, allowing Octavian to become Augustus and establish the Roman Empire that would endure for centuries.", wikipedia: "https://en.wikipedia.org/wiki/Final_War_of_the_Roman_Republic" },
  { year: 9, name: "Battle of the Teutoburg Forest", description: "Arminius led a coalition of Germanic tribes in a devastating ambush that completely destroyed three Roman legions under Varus, shocking Rome and permanently halting Roman expansion into Germany beyond the Rhine frontier.", wikipedia: "https://en.wikipedia.org/wiki/Battle_of_the_Teutoburg_Forest" },
  { year: 66, name: "First Jewish-Roman War", description: "The Great Jewish Revolt against Roman rule culminated in the devastating siege and destruction of Jerusalem and the Second Temple in 70 CE, ending the ancient Jewish state and dispersing the Jewish population throughout the Roman Empire in what became known as the Diaspora.", wikipedia: "https://en.wikipedia.org/wiki/First_Jewish%E2%80%93Roman_War" },
  { year: 101, name: "Dacian Wars", description: "Emperor Trajan's conquest of the wealthy Dacian kingdom under King Decebalus brought enormous gold reserves to Rome and extended the empire to its greatest territorial extent, while also establishing Roman culture in what is now Romania.", wikipedia: "https://en.wikipedia.org/wiki/Dacian_Wars" },
  { year: 132, name: "Bar Kokhba Revolt", description: "The final major Jewish revolt against Roman rule under the leadership of Simon bar Kokhba resulted in catastrophic defeat, the complete destruction of Jerusalem as Aelia Capitolina, and the official beginning of the Jewish Diaspora as Jews were banned from their homeland.", wikipedia: "https://en.wikipedia.org/wiki/Bar_Kokhba_revolt" },
  { year: 235, name: "Crisis of the Third Century", description: "Fifty years of continuous civil wars, barbarian invasions, plague, and economic collapse nearly destroyed the Roman Empire as over 50 emperors claimed power, most dying violent deaths, until Diocletian's reforms restored stability.", wikipedia: "https://en.wikipedia.org/wiki/Crisis_of_the_Third_Century" },
  { year: 376, name: "Gothic War", description: "The Visigothic crossing of the Danube River marked the beginning of the great barbarian migrations that would ultimately lead to the fall of the Western Roman Empire, as desperate Gothic refugees fleeing the Huns sought sanctuary in Roman territory.", wikipedia: "https://en.wikipedia.org/wiki/Gothic_War_(376%E2%80%93382)" },
  { year: 378, name: "Battle of Adrianople", description: "The catastrophic Roman defeat at Adrianople where Emperor Valens was killed along with two-thirds of his army marked the beginning of Rome's irreversible military decline and demonstrated that barbarian forces could decisively defeat Roman legions in open battle.", wikipedia: "https://en.wikipedia.org/wiki/Battle_of_Adrianople" },
  { year: 410, name: "Sack of Rome by Visigoths", description: "Alaric I's three-day sack of Rome shocked the ancient world and shattered the myth of Roman invincibility, marking a symbolic turning point in the decline of the Western Roman Empire as barbarian armies could now successfully assault the Eternal City.", wikipedia: "https://en.wikipedia.org/wiki/Sack_of_Rome_(410)" },
  { year: 476, name: "Fall of Western Roman Empire", description: "Germanic chieftain Odoacer's deposition of the last Western Roman Emperor Romulus Augustulus traditionally marks the end of the Western Roman Empire, though the Eastern Byzantine Empire would continue for another thousand years.", wikipedia: "https://en.wikipedia.org/wiki/Fall_of_the_Western_Roman_Empire" },
  { year: 533, name: "Vandalic War", description: "Byzantine Emperor Justinian's successful reconquest of North Africa from the Vandals under the brilliant general Belisarius represented the beginning of his ambitious attempt to restore the Roman Empire to its former glory and reclaim the western territories.", wikipedia: "https://en.wikipedia.org/wiki/Vandalic_War" },
  { year: 535, name: "Gothic War in Italy", description: "Justinian's costly 20-year attempt to reconquer Italy from the Ostrogoths ultimately succeeded but devastated the Italian peninsula economically and demographically, weakening Byzantine resources for future challenges from Arabs and other enemies.", wikipedia: "https://en.wikipedia.org/wiki/Gothic_War_(535%E2%80%93554)" },
  { year: 622, name: "Ridda Wars", description: "The succession crisis following Prophet Muhammad's death led to the Ridda Wars, where the first Caliph Abu Bakr fought to maintain Muslim unity and prevent the fragmentation of the early Islamic state as various Arabian tribes attempted to break away from central authority.", wikipedia: "https://en.wikipedia.org/wiki/Ridda_wars" },
  { year: 632, name: "Muslim Conquest of the Sassanid Empire", description: "Arab armies under brilliant generals like Khalid ibn al-Walid conquered the mighty Persian Sassanid Empire in a series of lightning campaigns, spreading Islam from the Arabian Peninsula to Central Asia and fundamentally transforming the region's religious and cultural landscape.", wikipedia: "https://en.wikipedia.org/wiki/Muslim_conquest_of_Persia" },
  { year: 636, name: "Muslim Conquest of the Levant", description: "The decisive Battle of Yarmouk and subsequent campaigns brought Syria, Palestine, and the Levant under Muslim control, ending centuries of Byzantine rule and establishing Islamic dominance in the region that continues to this day.", wikipedia: "https://en.wikipedia.org/wiki/Muslim_conquest_of_the_Levant" },
  { year: 711, name: "Muslim Conquest of Hispania", description: "Tariq ibn Ziyad's crossing of the strait that now bears his name (Gibraltar) led to the rapid Muslim conquest of most of the Iberian Peninsula, establishing Al-Andalus and beginning eight centuries of Islamic rule in Spain.", wikipedia: "https://en.wikipedia.org/wiki/Umayyad_conquest_of_Hispania" },
  { year: 732, name: "Battle of Tours", description: "Charles Martel's decisive victory over the Umayyad forces at Tours halted Muslim expansion into Western Europe, preserving Christian rule in France and potentially altering the entire course of European history and religious development.", wikipedia: "https://en.wikipedia.org/wiki/Battle_of_Tours" },
  { year: 793, name: "Viking Age Begins", description: "The Viking raid on the monastery of Lindisfarne marked the beginning of the Viking Age, as Scandinavian warriors and traders began their centuries-long expansion across Europe, establishing settlements from Iceland to Constantinople and fundamentally shaping medieval European development.", wikipedia: "https://en.wikipedia.org/wiki/Viking_Age" },
  { year: 845, name: "Viking Siege of Paris", description: "Ragnar Lodbrok's Vikings sailed up the Seine River and besieged Paris, forcing the Frankish King Charles the Bald to pay an enormous tribute of 7,000 pounds of silver, demonstrating Viking naval mobility and the vulnerability of European coastal cities.", wikipedia: "https://en.wikipedia.org/wiki/Siege_of_Paris_(845)" },
  { year: 1066, name: "Norman Conquest of England", description: "William the Conqueror's victory at the Battle of Hastings fundamentally transformed English society, language, law, and culture, replacing the Anglo-Saxon aristocracy with Norman French rulers and connecting England more closely to continental European politics.", wikipedia: "https://en.wikipedia.org/wiki/Norman_Conquest" },
  { year: 1071, name: "Battle of Manzikert", description: "The catastrophic Byzantine defeat at Manzikert opened Anatolia to Turkish settlement and marked the beginning of the end for Byzantine power in Asia Minor, fundamentally altering the balance of power between Christianity and Islam in the region.", wikipedia: "https://en.wikipedia.org/wiki/Battle_of_Manzikert" },
  { year: 1095, name: "First Crusade", description: "Pope Urban II's call for the First Crusade launched two centuries of religious warfare between Christians and Muslims, ultimately establishing Crusader states in the Holy Land and permanently altering relations between East and West.", wikipedia: "https://en.wikipedia.org/wiki/First_Crusade" },
  { year: 1187, name: "Saladin's Conquest of Jerusalem", description: "Saladin's decisive victory at the Battle of Hattin and subsequent recapture of Jerusalem from the Crusaders sparked the Third Crusade and demonstrated Muslim military resurgence, while his chivalrous treatment of Christian prisoners earned him respect even from his enemies.", wikipedia: "https://en.wikipedia.org/wiki/Siege_of_Jerusalem_(1187)" },
  { year: 1204, name: "Fourth Crusade", description: "The Fourth Crusade's shocking diversion to Constantinople resulted in the sack of the world's greatest Christian city by fellow Christians, fatally weakening the Byzantine Empire and permanently damaging relations between Eastern and Western Christianity.", wikipedia: "https://en.wikipedia.org/wiki/Fourth_Crusade" },
  { year: 1206, name: "Mongol Conquests Begin", description: "Temüjin's unification of the Mongol tribes as Genghis Khan launched the creation of the largest contiguous land empire in human history, stretching from Eastern Europe to the Pacific and fundamentally reshaping Eurasian trade and culture.", wikipedia: "https://en.wikipedia.org/wiki/Mongol_conquest_of_the_Jin_dynasty" },
  { year: 1241, name: "Mongol Invasion of Europe", description: "Mongol armies under Batu Khan devastated Poland and Hungary with revolutionary military tactics, reaching as far as modern-day Germany before mysteriously withdrawing, leaving Europe trembling at the edge of conquest.", wikipedia: "https://en.wikipedia.org/wiki/Mongol_invasion_of_Europe" },
  { year: 1258, name: "Mongol Siege of Baghdad", description: "Hulagu Khan's brutal sack of Baghdad destroyed the House of Wisdom and ended the Islamic Golden Age, massacring hundreds of thousands and effectively terminating the Abbasid Caliphate's thousand-year reign.", wikipedia: "https://en.wikipedia.org/wiki/Siege_of_Baghdad_(1258)" },
  { year: 1337, name: "Hundred Years' War", description: "The epic struggle between England and France over dynastic claims transformed medieval warfare through innovations like the longbow and gunpowder, while fostering national identities that persist today.", wikipedia: "https://en.wikipedia.org/wiki/Hundred_Years%27_War" },
  { year: 1347, name: "Black Death", description: "The bubonic plague pandemic killed one-third of Europe's population, causing massive social upheaval, weakening feudalism, empowering peasants, and fundamentally altering European society and economy.", wikipedia: "https://en.wikipedia.org/wiki/Black_Death" },
  { year: 1453, name: "Fall of Constantinople", description: "Sultan Mehmed II's conquest of Constantinople with massive cannons ended the thousand-year Byzantine Empire, completed Ottoman control of the Eastern Mediterranean, and symbolically marked the end of the Middle Ages.", wikipedia: "https://en.wikipedia.org/wiki/Fall_of_Constantinople" },
  { year: 1455, name: "Wars of the Roses", description: "The dynastic civil wars between the Houses of York and Lancaster devastated the English nobility and ultimately led to the Tudor dynasty's rise, strengthening royal power and ending the feudal age in England.", wikipedia: "https://en.wikipedia.org/wiki/Wars_of_the_Roses" },
  { year: 1494, name: "Italian Wars", description: "The Italian Wars saw major European powers France, Spain, and the Holy Roman Empire battle for control of wealthy Italian city-states, introducing gunpowder weapons and artillery that revolutionized siege warfare and military tactics.", wikipedia: "https://en.wikipedia.org/wiki/Italian_Wars" },
  { year: 1519, name: "Spanish Conquest of the Aztec Empire", description: "Hernán Cortés' audacious conquest of the mighty Aztec Empire with only a few hundred conquistadors, aided by indigenous allies and devastating European diseases, marked the beginning of Spanish colonial dominance in the Americas and the destruction of advanced Mesoamerican civilizations.", wikipedia: "https://en.wikipedia.org/wiki/Spanish_conquest_of_the_Aztec_Empire" },
  { year: 1532, name: "Spanish Conquest of the Inca Empire", description: "Francisco Pizarro's conquest of the vast Inca Empire through treachery, superior weapons, and epidemic diseases completed Spanish domination of South America and brought enormous wealth to Spain through the exploitation of silver mines like Potosí.", wikipedia: "https://en.wikipedia.org/wiki/Spanish_conquest_of_the_Inca_Empire" },
  { year: 1566, name: "Dutch Revolt", description: "The Netherlands' rebellion against Spanish rule, sparked by religious persecution and heavy taxation, eventually led to Dutch independence and the creation of the first modern republic, while establishing the Dutch as a major maritime and commercial power.", wikipedia: "https://en.wikipedia.org/wiki/Dutch_Revolt" },
  { year: 1618, name: "Thirty Years' War", description: "Beginning as a religious conflict between Catholic and Protestant states in the Holy Roman Empire, this devastating war killed millions, devastated Central Europe, and ended with the Peace of Westphalia that established the modern principle of national sovereignty.", wikipedia: "https://en.wikipedia.org/wiki/Thirty_Years%27_War" },
  { year: 1642, name: "English Civil War", description: "Parliament's war against King Charles I over royal authority and religious issues culminated in the king's execution and the establishment of a republic under Oliver Cromwell, fundamentally altering the balance of power between monarchy and parliament in England.", wikipedia: "https://en.wikipedia.org/wiki/English_Civil_War" },
  { year: 1700, name: "Great Northern War", description: "The coalition war against Sweden's Charles XII ended Swedish dominance in the Baltic and established Russia under Peter the Great as a major European power, fundamentally shifting the balance of power in Northern and Eastern Europe.", wikipedia: "https://en.wikipedia.org/wiki/Great_Northern_War" },
  { year: 1756, name: "Seven Years' War", description: "Often called the first truly global war, this conflict was fought on multiple continents between European powers and their colonies, ultimately reshaping colonial empires and establishing British dominance in North America and India.", wikipedia: "https://en.wikipedia.org/wiki/Seven_Years%27_War" },
  { year: 1775, name: "American Revolutionary War", description: "The thirteen American colonies' successful war for independence from Britain created the first modern democratic republic and inspired revolutionary movements worldwide, while establishing principles of self-governance that would influence global politics for centuries.", wikipedia: "https://en.wikipedia.org/wiki/American_Revolutionary_War" },
  { year: 1789, name: "French Revolution", description: "The popular revolution that overthrew the French monarchy unleashed democratic and nationalist ideals across Europe, fundamentally challenging the old order of absolute monarchy and aristocratic privilege while inspiring both liberating and terrifying revolutionary movements.", wikipedia: "https://en.wikipedia.org/wiki/French_Revolution" },
  { year: 1803, name: "Napoleonic Wars", description: "Napoleon Bonaparte's conquests reshaped the map of Europe and spread revolutionary principles across the continent, while his eventual defeat established a new balance of power that would last until World War I and created the modern European state system.", wikipedia: "https://en.wikipedia.org/wiki/Napoleonic_Wars" },
  { year: 1821, name: "Greek War of Independence", description: "The Greek struggle for independence from the Ottoman Empire captured the imagination of European intellectuals and marked the beginning of nationalist movements that would eventually dismember the Ottoman Empire while inspiring liberation movements across the Balkans.", wikipedia: "https://en.wikipedia.org/wiki/Greek_War_of_Independence" },
  { year: 1853, name: "Crimean War", description: "This modern war featuring new technologies like rifled muskets, explosive shells, and the telegraph highlighted the need for military and medical reforms, while Florence Nightingale's nursing work revolutionized battlefield medicine and hospital care.", wikipedia: "https://en.wikipedia.org/wiki/Crimean_War" },
  { year: 1861, name: "American Civil War", description: "The Union's victory over the Confederacy preserved the United States as a single nation, ended slavery, and demonstrated the power of industrial warfare, while defining modern America's commitment to equality and federal unity.", wikipedia: "https://en.wikipedia.org/wiki/American_Civil_War" },
  { year: 1870, name: "Franco-Prussian War", description: "Prussia's decisive victory over France unified the German states into the German Empire, fundamentally altering the European balance of power and creating the conditions that would eventually lead to World War I.", wikipedia: "https://en.wikipedia.org/wiki/Franco-Prussian_War" },
  { year: 1899, name: "Second Boer War", description: "Britain's controversial conquest of the Boer republics in South Africa introduced concentration camps for civilians and guerrilla warfare tactics, while demonstrating the challenges of imperial control in the face of determined local resistance.", wikipedia: "https://en.wikipedia.org/wiki/Second_Boer_War" },
  { year: 1904, name: "Russo-Japanese War", description: "Japan's stunning victory over Russia shocked the world by demonstrating that an Asian power could defeat a major European empire, inspiring nationalist movements across Asia and Africa while revealing Russia's military weakness.", wikipedia: "https://en.wikipedia.org/wiki/Russo-Japanese_War" },
  { year: 1912, name: "Balkan Wars", description: "The complex ethnic and territorial conflicts in the Balkans created a powder keg of instability, alliances, and grievances that would trigger World War I when Archduke Franz Ferdinand was assassinated in Sarajevo.", wikipedia: "https://en.wikipedia.org/wiki/Balkan_Wars" },
  { year: 1914, name: "World War I", description: "The Great War's unprecedented industrial slaughter killed over 16 million people, toppled four empires (German, Austro-Hungarian, Russian, and Ottoman), redrew the world map, and set the stage for even greater conflicts to come.", wikipedia: "https://en.wikipedia.org/wiki/World_War_I" },
  { year: 1917, name: "Russian Revolution", description: "The Bolsheviks' overthrow of the Tsarist regime created the world's first communist state, inspiring revolutionary movements worldwide while beginning an ideological struggle that would dominate the 20th century.", wikipedia: "https://en.wikipedia.org/wiki/Russian_Revolution" },
  { year: 1918, name: "Spanish Flu Pandemic", description: "The H1N1 influenza pandemic killed an estimated 50-100 million people worldwide, more than World War I, and demonstrated how modern transportation could rapidly spread disease across all continents.", wikipedia: "https://en.wikipedia.org/wiki/1918_influenza_pandemic" },
  { year: 1931, name: "Japanese Invasion of Manchuria", description: "Japan's aggressive expansion into Chinese Manchuria marked the beginning of conflicts that would eventually merge into World War II, challenging the post-WWI international order and League of Nations authority.", wikipedia: "https://en.wikipedia.org/wiki/Japanese_invasion_of_Manchuria" },
  { year: 1936, name: "Spanish Civil War", description: "The Spanish Civil War served as a dress rehearsal for World War II, testing new weapons and military tactics while dividing the world along ideological lines as fascist and communist forces supported opposing sides in the conflict.", wikipedia: "https://en.wikipedia.org/wiki/Spanish_Civil_War" },
  { year: 1939, name: "World War II", description: "The deadliest conflict in human history killed 70-85 million people and fundamentally reshaped the global order, ending with the emergence of the United States and Soviet Union as superpowers and establishing the United Nations system.", wikipedia: "https://en.wikipedia.org/wiki/World_War_II" },
  { year: 1945, name: "Atomic Bombings of Japan", description: "The first and only use of nuclear weapons in warfare against Hiroshima and Nagasaki ended World War II in the Pacific and ushered in the atomic age, fundamentally changing international relations and military strategy.", wikipedia: "https://en.wikipedia.org/wiki/Atomic_bombings_of_Hiroshima_and_Nagasaki" },
  { year: 1946, name: "Cold War Begins", description: "The ideological and geopolitical conflict between the capitalist United States and communist Soviet Union dominated world politics for 45 years, shaping international relations, military strategy, and domestic policies across the globe.", wikipedia: "https://en.wikipedia.org/wiki/Cold_War" },
  { year: 1948, name: "Arab-Israeli War", description: "The first Arab-Israeli war following Israel's declaration of independence established Israel as a state while creating the Palestinian refugee crisis, setting the stage for decades of Middle Eastern conflict.", wikipedia: "https://en.wikipedia.org/wiki/1948_Arab%E2%80%93Israeli_War" },
  { year: 1950, name: "Korean War", description: "The first major proxy war of the Cold War ended in stalemate and permanently divided Korea, demonstrating the limits of superpower influence while establishing the pattern of limited conflicts during the nuclear age.", wikipedia: "https://en.wikipedia.org/wiki/Korean_War" },
  { year: 1954, name: "First Indochina War", description: "The Vietnamese victory over France at Dien Bien Phu ended European colonialism in Southeast Asia and demonstrated that determined guerrilla forces could defeat modern conventional armies, inspiring liberation movements worldwide.", wikipedia: "https://en.wikipedia.org/wiki/First_Indochina_War" },
  { year: 1956, name: "Suez Crisis", description: "The failed Anglo-French intervention in Egypt following Nasser's nationalization of the Suez Canal marked the definitive end of European colonial power and established American and Soviet dominance in global affairs.", wikipedia: "https://en.wikipedia.org/wiki/Suez_Crisis" },
  { year: 1962, name: "Cuban Missile Crisis", description: "The nuclear standoff between the United States and Soviet Union over Soviet missiles in Cuba brought the world closer to nuclear war than ever before or since, ultimately leading to improved communication and arms control agreements.", wikipedia: "https://en.wikipedia.org/wiki/Cuban_Missile_Crisis" },
  { year: 1964, name: "Vietnam War Escalation", description: "American military escalation in Vietnam under Lyndon Johnson became a defining conflict of the Cold War era, ultimately ending in American withdrawal and demonstrating the limits of superpower intervention in civil conflicts.", wikipedia: "https://en.wikipedia.org/wiki/Vietnam_War" },
  { year: 1967, name: "Six-Day War", description: "Israel's lightning victory over Arab neighbors in just six days transformed Middle Eastern geopolitics and borders, establishing Israeli control over the West Bank, Gaza Strip, and other territories that remain contentious today.", wikipedia: "https://en.wikipedia.org/wiki/Six-Day_War" },
  { year: 1973, name: "Yom Kippur War", description: "The Arab surprise attack on Israel during Judaism's holiest day initially succeeded but ultimately failed, leading to the oil embargo that transformed global economics and reshaping Middle Eastern alliances.", wikipedia: "https://en.wikipedia.org/wiki/Yom_Kippur_War" },
  { year: 1979, name: "Soviet-Afghan War", description: "The Soviet invasion of Afghanistan became the USSR's 'Vietnam,' draining resources and morale for a decade while contributing to the eventual collapse of the Soviet Union and rise of Islamic fundamentalism.", wikipedia: "https://en.wikipedia.org/wiki/Soviet%E2%80%93Afghan_War" },
  { year: 1980, name: "Iran-Iraq War", description: "The eight-year war between Iran and Iraq devastated both countries and destabilized the Persian Gulf region, featuring chemical weapons, human wave attacks, and massive casualties that scarred an entire generation.", wikipedia: "https://en.wikipedia.org/wiki/Iran%E2%80%93Iraq_War" },
  { year: 1982, name: "Falklands War", description: "The brief war between Britain and Argentina over remote South Atlantic islands boosted nationalist sentiment in both countries and demonstrated the continued relevance of conventional military power in the nuclear age.", wikipedia: "https://en.wikipedia.org/wiki/Falklands_War" },
  { year: 1991, name: "Gulf War", description: "The coalition forces' liberation of Kuwait from Iraq demonstrated the effectiveness of precision warfare technology and established American military supremacy in the post-Cold War world.", wikipedia: "https://en.wikipedia.org/wiki/Gulf_War" },
  { year: 1991, name: "Yugoslav Wars", description: "The ethnic conflicts that tore apart Yugoslavia brought genocide and war crimes back to Europe, challenging international law and leading to the development of new interventionist doctrines in humanitarian crises.", wikipedia: "https://en.wikipedia.org/wiki/Yugoslav_Wars" },
  { year: 1994, name: "Rwandan Genocide", description: "The 100-day genocide that killed approximately 800,000 people highlighted the international community's failure to prevent atrocities and led to reforms in international humanitarian intervention and peacekeeping.", wikipedia: "https://en.wikipedia.org/wiki/Rwandan_genocide" },
  { year: 2001, name: "War in Afghanistan", description: "The US-led invasion following the September 11 attacks became America's longest war, lasting 20 years and ending with the Taliban's return to power, raising questions about the effectiveness of military intervention in nation-building.", wikipedia: "https://en.wikipedia.org/wiki/War_in_Afghanistan_(2001%E2%80%932021)" },
  { year: 2003, name: "Iraq War", description: "The US-led invasion that toppled Saddam Hussein's regime was justified by claims of weapons of mass destruction that proved false, leading to years of insurgency, sectarian violence, and regional destabilization that continues to affect Middle Eastern politics.", wikipedia: "https://en.wikipedia.org/wiki/Iraq_War" },
  { year: 2011, name: "Arab Spring", description: "The wave of popular uprisings across the Arab world toppled long-standing dictators in Tunisia, Egypt, Libya, and Yemen but led to civil wars and instability, demonstrating both the power and limitations of grassroots democratic movements.", wikipedia: "https://en.wikipedia.org/wiki/Arab_Spring" },
  { year: 2014, name: "Russian Annexation of Crimea", description: "Russia's annexation of Crimea from Ukraine marked the return of territorial conquest in Europe and violated international law, leading to Western sanctions and fundamentally altering post-Cold War security arrangements.", wikipedia: "https://en.wikipedia.org/wiki/Annexation_of_Crimea_by_the_Russian_Federation" },
  { year: 2014, name: "Rise of ISIS", description: "The Islamic State's capture of vast territories in Iraq and Syria, along with its brutal tactics and global terrorist attacks, demonstrated how extremist groups could exploit power vacuums and use social media for recruitment and propaganda.", wikipedia: "https://en.wikipedia.org/wiki/Islamic_State" },
  { year: 2022, name: "Russian Invasion of Ukraine", description: "Putin's full-scale invasion of Ukraine marked the largest European war since World War II, reshaping global alliances, revitalizing NATO, and demonstrating the continued relevance of conventional warfare in the 21st century.", wikipedia: "https://en.wikipedia.org/wiki/Russian_invasion_of_Ukraine" },
  { year: 2023, name: "Israel-Gaza War", description: "Hamas's surprise attack on Israel followed by Israel's massive military response in Gaza created a humanitarian crisis and reignited global debates about the Israeli-Palestinian conflict, international law, and civilian protection in warfare.", wikipedia: "https://en.wikipedia.org/wiki/Israel%E2%80%93Hamas_war" },
  { year: 2024, name: "Global Cyber Conflicts", description: "State-sponsored cyber attacks on critical infrastructure, electoral systems, and civilian targets have emerged as a new form of warfare, with nations like Russia, China, Iran, and North Korea conducting sophisticated digital operations against adversaries.", wikipedia: "https://en.wikipedia.org/wiki/Cyberwarfare" },
];

/**
 * Shuffle array using Fisher-Yates algorithm
 */
export function shuffleConflicts(conflicts) {
  const shuffled = [...conflicts];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

/**
 * Get a random subset of conflicts for the game
 */
export function getRandomConflictsSet(count = 20) {
  const shuffled = shuffleConflicts(historicalConflicts);
  return shuffled.slice(0, count);
}

/**
 * Sort conflicts by year (for verification)
 */
export function sortConflictsByYear(conflicts) {
  return [...conflicts].sort((a, b) => a.year - b.year);
}
