/**
 * @fileoverview Data source for the Timeline Game containing 100 most important technological innovations
 * Each innovation includes the year, name, description, and Wikipedia link for educational purposes
 */

export const technologicalInnovations = [
  { year: -10000, name: "Agriculture", description: "The Neolithic Revolution marked humanity's transition from hunter-gatherer societies to permanent settlements through the domestication of plants and animals, enabling population growth, specialization, and the foundation of civilization.", wikipedia: "https://en.wikipedia.org/wiki/Agriculture" },
  { year: -3500, name: "The Wheel", description: "One of humanity's most revolutionary inventions, the wheel enabled efficient transportation, pottery making through the potter's wheel, and became fundamental to countless mechanical applications including pulleys, gears, and mills.", wikipedia: "https://en.wikipedia.org/wiki/Wheel" },
  { year: -3200, name: "Writing Systems", description: "The development of cuneiform in Mesopotamia and hieroglyphs in Egypt created the first recorded human languages, revolutionizing knowledge preservation, administration, law, and literature for future generations.", wikipedia: "https://en.wikipedia.org/wiki/Writing_system" },
  { year: -3000, name: "Bronze Metallurgy", description: "The discovery of bronze, an alloy of copper and tin, marked the beginning of the Bronze Age and advanced human toolmaking with stronger, more durable implements that transformed agriculture, warfare, and craftsmanship.", wikipedia: "https://en.wikipedia.org/wiki/Bronze" },
  { year: -2600, name: "Mathematics", description: "The development of decimal systems, geometry, and mathematical principles by ancient civilizations enabled remarkable engineering achievements like the Egyptian pyramids and laid the foundation for all future scientific advancement.", wikipedia: "https://en.wikipedia.org/wiki/Mathematics" },
  { year: -1200, name: "Iron Smelting", description: "The mastery of iron smelting launched the Iron Age, providing stronger and more abundant materials for tools and weapons than bronze, transforming agriculture, warfare, and construction across civilizations.", wikipedia: "https://en.wikipedia.org/wiki/Iron_smelting" },
  { year: -800, name: "Alphabet", description: "The development of phonetic alphabetic writing systems, particularly by the Phoenicians and Greeks, democratized literacy by making writing more accessible and accelerated the transfer of knowledge across cultures.", wikipedia: "https://en.wikipedia.org/wiki/Alphabet" },
  { year: -500, name: "Optics", description: "Ancient Greek and Chinese understanding of light refraction and the creation of the first optical lenses laid the groundwork for telescopes, microscopes, and modern optical science.", wikipedia: "https://en.wikipedia.org/wiki/Optics" },
  { year: 100, name: "Paper Manufacturing", description: "Invented in China, paper provided a mass-producible, lightweight writing medium that revolutionized record-keeping, communication, and the spread of knowledge throughout the world.", wikipedia: "https://en.wikipedia.org/wiki/Paper" },
  { year: 600, name: "Windmill", description: "The first practical renewable energy source for mechanical power beyond human and animal labor, windmills enabled grain processing, water pumping, and industrial applications that supported growing populations.", wikipedia: "https://en.wikipedia.org/wiki/Windmill" },
  { year: 700, name: "Gunpowder", description: "Invented in China, this chemical explosive fundamentally changed warfare tactics, enabled advanced mining operations, and later facilitated the development of firearms that reshaped global power dynamics.", wikipedia: "https://en.wikipedia.org/wiki/Gunpowder" },
  { year: 1000, name: "Mechanical Clockwork", description: "The development of precise mechanical timekeeping devices enabled accurate navigation, coordinated scientific observations, and synchronized social activities, becoming essential to modern civilization.", wikipedia: "https://en.wikipedia.org/wiki/Clock" },
  { year: 1040, name: "Magnetic Compass", description: "This crucial navigation breakthrough allowed mariners to determine direction regardless of weather conditions, enabling global exploration, trade expansion, and the Age of Discovery.", wikipedia: "https://en.wikipedia.org/wiki/Compass" },
  { year: 1440, name: "Printing Press", description: "Johannes Gutenberg's movable type printing press democratized access to knowledge, accelerated the Scientific Revolution and Reformation, and made books affordable for common people for the first time.", wikipedia: "https://en.wikipedia.org/wiki/Printing_press" },
  { year: 1543, name: "Heliocentric Model", description: "Nicolaus Copernicus's revolutionary astronomical model placed the Sun at the center of the solar system rather than Earth, fundamentally challenging medieval worldviews and laying the foundation for modern astronomy and the Scientific Revolution.", wikipedia: "https://en.wikipedia.org/wiki/Heliocentrism" },
  { year: 1608, name: "Optical Telescope", description: "The invention of the telescope enabled astronomical observations that revolutionized our understanding of the cosmos, allowing Galileo to observe Jupiter's moons and providing magnification technology that transformed navigation, warfare, and scientific discovery.", wikipedia: "https://en.wikipedia.org/wiki/Telescope" },
  { year: 1609, name: "Laws of Planetary Motion", description: "Johannes Kepler's three laws mathematically described how planets orbit the Sun in elliptical paths, providing the precise mathematical framework that supported the heliocentric model and enabled Newton's later work on universal gravitation.", wikipedia: "https://en.wikipedia.org/wiki/Kepler%27s_laws_of_planetary_motion" },
  { year: 1665, name: "Microscopy", description: "The development of compound microscopes revealed the microscopic world for the first time, founding the field of microbiology, enabling the discovery of cells and bacteria, and revolutionizing medicine through understanding of disease-causing microorganisms.", wikipedia: "https://en.wikipedia.org/wiki/Microscopy" },
  { year: 1687, name: "Universal Gravitation", description: "Isaac Newton's law of universal gravitation unified terrestrial and celestial mechanics, explaining both falling apples and planetary orbits through a single mathematical principle that dominated physics for over two centuries.", wikipedia: "https://en.wikipedia.org/wiki/Newton%27s_law_of_universal_gravitation" },
  { year: 1712, name: "Steam Engine", description: "Thomas Newcomen and later James Watt's improvements to the steam engine provided the first practical method of converting heat into mechanical work, launching the Industrial Revolution and transforming manufacturing, transportation, and society through mechanized power.", wikipedia: "https://en.wikipedia.org/wiki/Steam_engine" },
  { year: 1750, name: "Industrial Manufacturing", description: "The factory system and mechanization transformed production from handcraft to mass manufacturing, creating the modern industrial economy while fundamentally changing social structures, urbanization patterns, and economic relationships worldwide.", wikipedia: "https://en.wikipedia.org/wiki/Industrial_Revolution" },
  { year: 1769, name: "Steam Vehicle", description: "Nicolas-Joseph Cugnot's steam-powered tricycle became the first self-propelled land vehicle, beginning the transportation revolution that would eventually lead to automobiles, trains, and the mobility that defines modern society.", wikipedia: "https://en.wikipedia.org/wiki/Steam_car" },
  { year: 1783, name: "Human Flight", description: "The Montgolfier brothers' hot air balloon achieved humanity's ancient dream of flight, proving that humans could leave the ground and leading to aviation developments that would revolutionize transportation, warfare, and global connectivity.", wikipedia: "https://en.wikipedia.org/wiki/Hot_air_balloon" },
  { year: 1798, name: "Vaccination", description: "Edward Jenner's smallpox vaccine established the science of immunology and preventive medicine, saving millions of lives and providing the foundation for modern vaccination programs that prevent diseases and enable public health.", wikipedia: "https://en.wikipedia.org/wiki/Vaccination" },
  { year: 1800, name: "Electric Battery", description: "Alessandro Volta's battery provided the first reliable source of electric current, enabling electrochemistry, the telegraph, and laying the foundation for all electrical technology that would transform the modern world.", wikipedia: "https://en.wikipedia.org/wiki/Electric_battery" },
  { year: 1804, name: "Railway Locomotive", description: "Richard Trevithick's steam-powered locomotive revolutionized land transportation and commerce by enabling rapid, heavy cargo transport, connecting distant regions and accelerating economic development through improved trade networks.", wikipedia: "https://en.wikipedia.org/wiki/Steam_locomotive" },
  { year: 1820, name: "Electromagnetism", description: "Hans Christian Oersted and Michael Faraday's discoveries revealed the fundamental connection between electricity and magnetism, leading to electric motors, generators, and the entire electrical power industry that powers modern civilization.", wikipedia: "https://en.wikipedia.org/wiki/Electromagnetism" },
  { year: 1826, name: "Photography", description: "The first permanent photographic images captured reality with unprecedented accuracy, transforming visual communication, documentation, journalism, and art while providing a means to preserve moments and share visual information across time and space.", wikipedia: "https://en.wikipedia.org/wiki/Photography" },
  { year: 1831, name: "Electromagnetic Induction", description: "Michael Faraday's discovery that changing magnetic fields generate electric current enabled the development of electric generators and transformers, making possible the electrical power grid that supplies energy to modern society.", wikipedia: "https://en.wikipedia.org/wiki/Electromagnetic_induction" },
  { year: 1837, name: "Electric Telegraph", description: "Samuel Morse's telegraph created the first instantaneous long-distance communication system, revolutionizing news transmission, business operations, and military coordination while shrinking the perceived size of the world through rapid information exchange.", wikipedia: "https://en.wikipedia.org/wiki/Electrical_telegraph" },
  { year: 1846, name: "Surgical Anesthesia", description: "The introduction of ether and chloroform for pain-free surgery revolutionized medicine by enabling complex operations previously impossible due to patient suffering, dramatically reducing surgical mortality and advancing medical procedures.", wikipedia: "https://en.wikipedia.org/wiki/Anesthesia" },
  { year: 1859, name: "Evolution by Natural Selection", description: "Charles Darwin's theory revolutionized biology by providing a scientific explanation for the diversity of life, fundamentally changing humanity's understanding of its origins and relationship to other living organisms through evidence-based natural processes.", wikipedia: "https://en.wikipedia.org/wiki/Evolution" },
  { year: 1859, name: "Oil Refining", description: "The petroleum industry launched with oil drilling and refining techniques, providing energy sources that would power internal combustion engines, heating systems, and petrochemical industries essential to modern civilization.", wikipedia: "https://en.wikipedia.org/wiki/Oil_refinery" },
  { year: 1865, name: "Germ Theory", description: "Louis Pasteur's proof that microorganisms cause disease revolutionized medicine and hygiene, leading to antiseptic practices, sterilization techniques, and the understanding that cleanliness prevents infection and saves lives.", wikipedia: "https://en.wikipedia.org/wiki/Germ_theory_of_disease" },
  { year: 1866, name: "Genetic Inheritance", description: "Gregor Mendel's laws of heredity through pea plant experiments laid the foundation for genetics by demonstrating how traits pass from parents to offspring, establishing the basis for understanding heredity, breeding, and later genetic engineering.", wikipedia: "https://en.wikipedia.org/wiki/Mendelian_inheritance" },
  { year: 1869, name: "Periodic Table", description: "Dmitri Mendeleev's organization of chemical elements by atomic weight revealed periodic patterns in their properties, enabling the prediction of undiscovered elements and providing the fundamental framework for understanding chemical behavior and reactions.", wikipedia: "https://en.wikipedia.org/wiki/Periodic_table" },
  { year: 1876, name: "Telephone", description: "Alexander Graham Bell's telephone enabled voice communication over long distances, transforming society and business by allowing instant spoken communication between distant locations and laying the foundation for global telecommunications.", wikipedia: "https://en.wikipedia.org/wiki/Telephone" },
  { year: 1879, name: "Electric Lighting", description: "Thomas Edison's practical incandescent light bulb brought safe, reliable artificial light to the masses, extending productive hours, improving quality of life, and enabling the development of modern cities and night-time activities.", wikipedia: "https://en.wikipedia.org/wiki/Incandescent_light_bulb" },
  { year: 1885, name: "Internal Combustion Engine", description: "The gasoline-powered internal combustion engine enabled automobiles, motorcycles, and eventually powered flight, revolutionizing transportation and mobility while providing portable power that transformed industry and personal freedom.", wikipedia: "https://en.wikipedia.org/wiki/Internal_combustion_engine" },
  { year: 1886, name: "Automobile", description: "Karl Benz's motorized vehicle transformed society, cities, and commerce by providing personal transportation that reshaped urban planning, created new industries, and fundamentally changed how people live, work, and interact with their environment.", wikipedia: "https://en.wikipedia.org/wiki/Automobile" },
  { year: 1895, name: "X-Ray Imaging", description: "Wilhelm Röntgen's discovery of X-rays revolutionized medical diagnosis by allowing doctors to see inside the human body without surgery, enabling the detection of broken bones, diseases, and internal injuries.", wikipedia: "https://en.wikipedia.org/wiki/X-ray" },
  { year: 1896, name: "Radioactivity", description: "Henri Becquerel's discovery of radioactivity opened nuclear physics, leading to understanding of atomic structure, nuclear energy, medical treatments using radiation, and revolutionary insights into the nature of matter and energy.", wikipedia: "https://en.wikipedia.org/wiki/Radioactivity" },
  { year: 1897, name: "Radio Waves", description: "Guglielmo Marconi's wireless communication using radio waves enabled global broadcasting and long-distance communication without cables, revolutionizing mass media, navigation, and emergency communications across the world.", wikipedia: "https://en.wikipedia.org/wiki/Radio" },
  { year: 1900, name: "Quantum Theory", description: "Max Planck's quantum hypothesis that energy comes in discrete packets revolutionized physics by explaining blackbody radiation and laying the foundation for quantum mechanics, which governs atomic and subatomic behavior.", wikipedia: "https://en.wikipedia.org/wiki/Quantum_mechanics" },
  { year: 1903, name: "Powered Flight", description: "The Wright brothers achieved the first controlled, sustained powered flight in human history, opening the age of aviation that would revolutionize transportation, warfare, commerce, and global connectivity through air travel.", wikipedia: "https://en.wikipedia.org/wiki/Wright_Flyer" },
  { year: 1905, name: "Relativity Theory", description: "Albert Einstein's special theory of relativity revolutionized concepts of space, time, and energy, introducing the famous equation E=mc² and fundamentally changing physics while enabling technologies like GPS and nuclear power.", wikipedia: "https://en.wikipedia.org/wiki/Special_relativity" },
  { year: 1908, name: "Assembly Line Production", description: "Henry Ford's moving assembly line made mass production efficient and affordable, revolutionizing manufacturing worldwide by reducing costs and production time while making consumer goods accessible to ordinary people.", wikipedia: "https://en.wikipedia.org/wiki/Assembly_line" },
  { year: 1915, name: "General Relativity", description: "Einstein's general theory of relativity described gravity as the curvature of spacetime, revolutionizing our understanding of the universe, predicting black holes, and providing the foundation for modern cosmology and astrophysics.", wikipedia: "https://en.wikipedia.org/wiki/General_relativity" },
  { year: 1919, name: "Nuclear Transmutation", description: "Ernest Rutherford achieved the first artificial splitting of an atomic nucleus, proving that elements could be transformed into other elements and opening the path to nuclear energy, atomic weapons, and nuclear medicine.", wikipedia: "https://en.wikipedia.org/wiki/Nuclear_transmutation" },
  { year: 1928, name: "Antibiotics", description: "Alexander Fleming's discovery of penicillin revolutionized medicine by providing the first effective treatment against bacterial infections, saving millions of lives and making modern surgery, organ transplants, and chemotherapy safe and possible.", wikipedia: "https://en.wikipedia.org/wiki/Antibiotic" },
  { year: 1929, name: "Expanding Universe", description: "Edwin Hubble's discovery that the universe is expanding led to the Big Bang theory, revolutionizing cosmology and our understanding of the universe's origin, age, and ultimate fate while providing evidence for the cosmic creation event.", wikipedia: "https://en.wikipedia.org/wiki/Hubble%27s_law" },
  { year: 1935, name: "Radar Technology", description: "Radio detection and ranging revolutionized navigation, weather prediction, and military defense by using radio waves to detect distant objects, enabling safer aviation, storm tracking, and early warning systems.", wikipedia: "https://en.wikipedia.org/wiki/Radar" },
  { year: 1938, name: "Nuclear Fission", description: "Otto Hahn and Fritz Strassmann's discovery that splitting atomic nuclei releases enormous energy led to nuclear power plants that generate electricity and nuclear weapons that changed global politics and warfare.", wikipedia: "https://en.wikipedia.org/wiki/Nuclear_fission" },
  { year: 1942, name: "Controlled Nuclear Reaction", description: "Enrico Fermi's first nuclear reactor demonstrated controlled atomic energy, proving that nuclear fission could be harnessed for peaceful purposes, leading to nuclear power generation and medical isotope production.", wikipedia: "https://en.wikipedia.org/wiki/Chicago_Pile-1" },
  { year: 1944, name: "Digital Computer", description: "Colossus and ENIAC, the first programmable digital computers, launched the computer age by demonstrating that machines could perform complex calculations and logical operations, laying the foundation for the digital revolution that transformed every aspect of modern life.", wikipedia: "https://en.wikipedia.org/wiki/Digital_computer" },
  { year: 1947, name: "Transistor", description: "The invention of the transistor at Bell Labs enabled solid-state electronics, replacing bulky vacuum tubes with tiny, reliable switches that made possible integrated circuits, personal computers, smartphones, and the entire digital technology revolution.", wikipedia: "https://en.wikipedia.org/wiki/Transistor" },
  { year: 1953, name: "DNA Double Helix", description: "James Watson and Francis Crick's discovery of DNA's double helix structure revealed life's genetic code, enabling understanding of heredity, genetic engineering, biotechnology, and personalized medicine while revolutionizing biology and medicine.", wikipedia: "https://en.wikipedia.org/wiki/DNA" },
  { year: 1957, name: "Space Satellite", description: "Sputnik 1 launched the space age and satellite technology, proving that artificial objects could orbit Earth and leading to satellite communications, GPS navigation, weather monitoring, and space exploration that connects the global community.", wikipedia: "https://en.wikipedia.org/wiki/Sputnik_1" },
  { year: 1958, name: "Integrated Circuit", description: "The microchip enabled miniaturization and the computer revolution by placing multiple transistors on a single piece of silicon, making possible personal computers, smartphones, and all modern electronic devices through compact, powerful processing.", wikipedia: "https://en.wikipedia.org/wiki/Integrated_circuit" },
  { year: 1960, name: "Laser", description: "The laser produces coherent light with applications ranging from precision surgery and industrial cutting to fiber optic communications and scientific research, revolutionizing manufacturing, medicine, and information technology through focused light energy.", wikipedia: "https://en.wikipedia.org/wiki/Laser" },
  { year: 1961, name: "Human Spaceflight", description: "Yuri Gagarin's orbital flight proved that humans could survive in space, opening the era of human space exploration that led to moon landings, space stations, and the possibility of interplanetary travel and colonization.", wikipedia: "https://en.wikipedia.org/wiki/Human_spaceflight" },
  { year: 1969, name: "Computer Networking", description: "ARPANET connected computers over long distances, leading to the Internet that revolutionized communication, commerce, education, and information access by creating a global network that connects billions of people and devices.", wikipedia: "https://en.wikipedia.org/wiki/ARPANET" },
  { year: 1969, name: "Moon Landing", description: "Apollo 11's successful moon landing demonstrated humanity's capability for interplanetary travel, inspiring technological innovation and showing that seemingly impossible goals could be achieved through science, engineering, and determination.", wikipedia: "https://en.wikipedia.org/wiki/Apollo_11" },
  { year: 1971, name: "Microprocessor", description: "The CPU on a chip enabled Personal computers and digital devices by placing the computer's central processing unit on a single integrated circuit, making computing power affordable and accessible to individuals and small businesses.", wikipedia: "https://en.wikipedia.org/wiki/Microprocessor" },
  { year: 1973, name: "Genetic Engineering", description: "The first recombinant DNA techniques launched biotechnology by enabling scientists to modify genetic material, leading to genetically modified crops, synthetic insulin, gene therapy, and the potential to cure genetic diseases.", wikipedia: "https://en.wikipedia.org/wiki/Genetic_engineering" },
  { year: 1975, name: "Personal Computer", description: "The Altair 8800 and other early personal computers democratized computing power for individuals and small businesses, making computer technology accessible beyond large corporations and universities, leading to the personal computing revolution.", wikipedia: "https://en.wikipedia.org/wiki/Personal_computer" },
  { year: 1981, name: "PC Architecture", description: "The IBM PC established standard architecture that created the modern computer industry, enabling software compatibility, hardware standardization, and the growth of the personal computer market through common specifications.", wikipedia: "https://en.wikipedia.org/wiki/IBM_Personal_Computer" },
  { year: 1983, name: "Internet Protocol", description: "TCP/IP protocols enabled global computer networking by providing standard communication methods that allowed different computer networks to interconnect, creating the modern Internet that connects billions of devices worldwide.", wikipedia: "https://en.wikipedia.org/wiki/Internet_protocol_suite" },
  { year: 1989, name: "World Wide Web", description: "Tim Berners-Lee's hyperlinked information system transformed communication by creating an easy-to-use interface for the Internet, enabling global information sharing, e-commerce, social media, and the digital economy.", wikipedia: "https://en.wikipedia.org/wiki/World_Wide_Web" },
  { year: 1990, name: "Human Genome Project", description: "The international effort to map human DNA began a revolution in personalized medicine, genetic testing, and understanding human biology, leading to targeted treatments for cancer, genetic diseases, and precision medicine.", wikipedia: "https://en.wikipedia.org/wiki/Human_Genome_Project" },
  { year: 1993, name: "Global Positioning System", description: "Satellite navigation technology revolutionized location services by providing precise positioning anywhere on Earth, enabling GPS devices, smartphone navigation, autonomous vehicles, and location-based services that guide modern transportation.", wikipedia: "https://en.wikipedia.org/wiki/Global_Positioning_System" },
  { year: 1996, name: "Cloning", description: "Dolly the sheep proved that mammalian reproductive cloning was possible, advancing understanding of cellular biology and development while raising ethical questions about cloning applications in medicine and agriculture.", wikipedia: "https://en.wikipedia.org/wiki/Cloning" },
  { year: 1998, name: "Search Engine", description: "Google's PageRank algorithm organized the world's information by ranking web pages based on relevance and authority, making Internet information searchable and accessible while creating the foundation for the digital information economy.", wikipedia: "https://en.wikipedia.org/wiki/Google_Search" },
  { year: 2001, name: "Wikipedia", description: "The collaborative encyclopedia democratized knowledge creation by allowing anyone to contribute and edit articles, creating the largest repository of human knowledge while demonstrating the power of crowd-sourced information.", wikipedia: "https://en.wikipedia.org/wiki/Wikipedia" },
  { year: 2003, name: "Human Genome Sequencing", description: "The completion of the Human Genome Project mapped the complete human genetic code, enabling personalized medicine, genetic testing, and treatments based on individual genetic profiles while advancing understanding of human evolution and disease.", wikipedia: "https://en.wikipedia.org/wiki/Human_genome" },
  { year: 2004, name: "Social Networking", description: "Facebook and other social networks connected billions of people worldwide, transforming social interaction, communication, business marketing, and information sharing while creating new forms of digital community and cultural exchange.", wikipedia: "https://en.wikipedia.org/wiki/Social_networking_service" },
  { year: 2007, name: "Smartphone", description: "The iPhone created pocket computers that combined communication, computing, and internet access in a single device, transforming daily life through apps, mobile internet, digital photography, and constant connectivity.", wikipedia: "https://en.wikipedia.org/wiki/Smartphone" },
  { year: 2008, name: "Blockchain", description: "Bitcoin's distributed ledger technology enabled cryptocurrencies and decentralized systems by creating tamper-proof digital records without central authority, revolutionizing concepts of money, contracts, and trust in digital transactions.", wikipedia: "https://en.wikipedia.org/wiki/Blockchain" },
  { year: 2012, name: "CRISPR Gene Editing", description: "The precise DNA editing tool revolutionized genetic engineering by enabling accurate, efficient modification of genes in living organisms, offering potential cures for genetic diseases and new possibilities in medicine and agriculture.", wikipedia: "https://en.wikipedia.org/wiki/CRISPR" },
  { year: 2012, name: "Deep Learning", description: "Advanced neural networks achieved breakthrough artificial intelligence capabilities in image recognition, natural language processing, and pattern analysis, enabling AI systems that approach human-level performance in many cognitive tasks.", wikipedia: "https://en.wikipedia.org/wiki/Deep_learning" },
  { year: 2016, name: "Autonomous Vehicles", description: "Self-driving cars demonstrated AI navigation capabilities that could potentially reduce traffic accidents, improve transportation efficiency, and transform urban planning while raising questions about employment and technological dependence.", wikipedia: "https://en.wikipedia.org/wiki/Self-driving_car" },
  { year: 2016, name: "AlphaGo AI Breakthrough", description: "AlphaGo's victory over world Go champion demonstrated AI strategic thinking capabilities in complex games, showing that artificial intelligence could master tasks requiring intuition, creativity, and long-term planning.", wikipedia: "https://en.wikipedia.org/wiki/AlphaGo" },
  { year: 2019, name: "Quantum Supremacy", description: "Google's quantum computer outperformed classical computers on specific tasks, demonstrating quantum computing's potential to revolutionize cryptography, drug discovery, materials science, and optimization problems beyond classical computing limits.", wikipedia: "https://en.wikipedia.org/wiki/Quantum_supremacy" },
  { year: 2020, name: "mRNA Vaccines", description: "The rapid development of COVID-19 vaccines using messenger RNA technology demonstrated unprecedented speed in vaccine creation and opened new possibilities for treating cancer, genetic diseases, and future pandemics.", wikipedia: "https://en.wikipedia.org/wiki/MRNA_vaccine" },
  { year: 2022, name: "Large Language Models", description: "ChatGPT's public release demonstrated conversational artificial intelligence accessible to everyone, transforming how humans interact with computers and accelerating AI adoption across industries and education.", wikipedia: "https://en.wikipedia.org/wiki/Large_language_model" },
  { year: 2023, name: "Advanced AI Systems", description: "GPT-4 and other multimodal AI systems approached human-level reasoning in many domains, capable of processing text, images, and code while demonstrating emergent capabilities that surprised even their creators.", wikipedia: "https://en.wikipedia.org/wiki/GPT-4" },
  { year: 2024, name: "Commercial Space Travel", description: "Private companies like SpaceX, Blue Origin, and Virgin Galactic achieved routine civilian space transportation, making space accessible beyond government programs and opening new frontiers for commerce and exploration.", wikipedia: "https://en.wikipedia.org/wiki/Commercial_spaceflight" },
  { year: 2024, name: "Brain-Computer Interface", description: "Neuralink and similar technologies enabled direct neural control of computers and prosthetics, offering revolutionary treatment for paralysis and neurological conditions while raising profound questions about human enhancement.", wikipedia: "https://en.wikipedia.org/wiki/Brain%E2%80%93computer_interface" },
];

/**
 * Shuffle array using Fisher-Yates algorithm
 */
export function shuffleInnovations(innovations) {
  const shuffled = [...innovations];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

/*
 * Get a subset of innovations for shorter games
 */
export function getInnovationSubset(count = 20) {
  const shuffled = shuffleInnovations(technologicalInnovations);
  return shuffled.slice(0, count).sort((a, b) => a.year - b.year);
}
